# Generated by Django 5.2.4 on 2025-07-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('model_id', models.IntegerField()),
                ('path_file', models.CharField(max_length=355)),
                ('url_file', models.CharField(max_length=355)),
                ('ext', models.CharField(max_length=255)),
            ],
        ),
    ]
